services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "1000:1000"  # Keep this as-is if uid=1000
    group_add:
      - "992"  # render group
      - "44"   # video group
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - ./config:/config
      - ./cache:/cache
      - nfs-media:/media:ro
    ports:
      - "8096:8096"
    restart: unless-stopped

volumes:
  nfs-media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.10.11,rw,nfsvers=4
      device: ":/storage"
